# -*- Mode: Python -*-

Import('env')

if env['TGTTYPE'] == 'x86':
	env.AskatuCXXProg('sbin', target = 'uimng', source = env.Glob('*.cc'), LIBS = ['info', 'vbe'])
else:
	env.AskatuCXXProg('sbin', target = 'uimng', source = env.Glob('*.cc'), LIBS = ['info'])
