#!/bin/sh
. boot/$ASK_TGTTYPE/images.sh
create_mini_cd $1/dist $1/cd-mini.iso 0

cat >$1/config-$ASK_MAC <<EOF
root askatu
exec /boot/askatu root=/dev/iso9660-ramdisk-cd nosmp
load /bin/initloader
load /sbin/ramdisk /dev/ramdisk-cd -f /sys/boot/cd-mini.iso
load /sbin/pci /dev/pci
load /sbin/iso9660 /dev/iso9660-ramdisk-cd /dev/ramdisk-cd
load /cd-mini.iso
EOF

files="boot/askatu bin/initloader sbin/ramdisk sbin/iso9660 sbin/pci"
( cd $1/dist && rsync --progress -RLp $files $ASK_SERVER/askatu )
( cd $1 && rsync --progress -RLp cd-mini.iso $ASK_SERVER/askatu )
( cd $1 && rsync --progress -RLp config-$ASK_MAC $ASK_SERVER )
